In [69]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
import random

scaler = StandardScaler()

pd.set_option("display.max_rows", None)     # 행 제한 해제
pd.set_option("display.max_columns", None)  # 열 제한 해제
pd.set_option("display.width", None)        # 한 줄에 다 나오게
pd.set_option("display.max_colwidth", None) # 컬럼 길이 제한 해제

DATA_PATH = "./preprocess/03_processed_data/data_set.csv"
df = pd.read_csv(DATA_PATH, encoding="utf-8-sig")

In [70]:
# 분석에 안 쓰는 컬럼 제외
drop_cols = ["년도", "월", "지역"]
df = df.drop(columns=[c for c in drop_cols if c in df.columns])

# 숫자형 변수만 선택
num_df_ori = df.select_dtypes(include=[np.number]).dropna(how="any")

num_df_ori = pd.DataFrame(
    scaler.fit_transform(num_df_ori),
    columns=num_df_ori.columns,
    index=num_df_ori.index
)

# 피어슨 상관계수 행렬
corr = num_df_ori.corr(method="pearson")

In [71]:
def highlight_high_values(val):
    if abs(val) >= 0.8:
        return 'background-color: yellow; color: black;'
    return ''

# 적용
corr.style.applymap(highlight_high_values)

C:\Users\jeon\AppData\Local\Temp\ipykernel_24860\529615554.py:7: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  corr.style.applymap(highlight_high_values)

In [72]:
# 행렬을 긴 포맷으로 변환
corr_long = (
    corr.reset_index()
        .melt(id_vars="index", var_name="변수2", value_name="상관계수")
        .rename(columns={"index": "변수1"})
)
print(len(corr_long))
# 자기 자신과의 상관계수 제거
corr_long = corr_long[corr_long["변수1"] != corr_long["변수2"]]

# 변수1, 변수2 쌍 정렬해서 중복 제거
corr_long[["변수1", "변수2"]] = np.sort(corr_long[["변수1", "변수2"]], axis=1)
corr_long = corr_long.drop_duplicates(subset=["변수1", "변수2"])

# 상관계수 기준 정렬
corr_long = (
    corr_long[corr_long["상관계수"].abs() >= 0.8]  
    .sort_values(by=["변수1", "상관계수"], ascending=[True, False])  # 변수1 → 상관계수 순으로 정렬
    .reset_index(drop=True)
)

corr_long

1369

           변수1         변수2      상관계수
0     1회충전주행거리    차량전체_등록수  0.955616
1     1회충전주행거리    휘발유차_등록수  0.954499
2     1회충전주행거리      연료소비효율  0.925752
3     1회충전주행거리     경유차_등록수  0.922371
4     1회충전주행거리  하이브리드차_등록수  0.897079
5     1회충전주행거리   하이브리드차_순증  0.876350
6     1회충전주행거리     수소차_등록수  0.868247
7     1회충전주행거리   차량전체_순증가량  0.808240
8     1회충전주행거리         보조금 -0.886799
9          cpi      평균기준금리  0.942273
10     경유차_등록수    휘발유차_등록수  0.986626
11     경유차_등록수    차량전체_등록수  0.984596
12     경유차_등록수      연료소비효율  0.963058
13     경유차_등록수   차량전체_순증가량  0.911136
14     경유차_등록수   휘발유차_순증가량  0.833423
15     경유차_등록수  하이브리드차_등록수  0.813978
16     경유차_등록수   하이브리드차_순증  0.810180
17     경유차_등록수         보조금 -0.869332
18  급속충전기_누적대수  전체충전기_누적대수  0.947121
19  급속충전기_누적대수  완속충전기_누적대수  0.936288
20  급속충전기_누적대수  급속충전기_신규설치  0.861218
21  급속충전기_누적대수  전체충전기_신규설치  0.830850
22  급속충전기_누적대수  완속충전기_신규설치  0.819434
23  급속충전기_신규설치  전체충전기_신규설치  0.907375
24  급속충전기_신규설치  완속충전기_신규설치  0.888986
25  급속충전기_신규설치  전체충전기_누적대수  0.854163
26  급속충전기_신규설치  완속충전기_누적대수  0.848473
27        디젤가격       휘발유가격  0.903962
28   미세먼지10 수치  미세먼지2.5 수치  0.822713
29      민간공고대수        출고대수  0.982857
30         보조금     수소차_등록수 -0.824589
31         보조금   하이브리드차_순증 -0.831748
32         보조금  하이브리드차_등록수 -0.843287
33         보조금      연료소비효율 -0.892566
34         보조금    휘발유차_등록수 -0.898684
35         보조금    차량전체_등록수 -0.900565
36     수소차_등록수  하이브리드차_등록수  0.985576
37     수소차_등록수   하이브리드차_순증  0.961817
38     수소차_등록수    차량전체_등록수  0.873855
39     수소차_등록수    휘발유차_등록수  0.868432
40      연료소비효율    휘발유차_등록수  0.955987
41      연료소비효율    차량전체_등록수  0.954976
42      연료소비효율   차량전체_순증가량  0.875339
43  완속충전기_누적대수  전체충전기_누적대수  0.999480
44  완속충전기_누적대수  전체충전기_신규설치  0.897827
45  완속충전기_누적대수  완속충전기_신규설치  0.893673
46  완속충전기_신규설치  전체충전기_신규설치  0.999124
47  완속충전기_신규설치  전체충전기_누적대수  0.891621
48  전체충전기_누적대수  전체충전기_신규설치  0.896464
49    차량전체_등록수    휘발유차_등록수  0.999922
50    차량전체_등록수  하이브리드차_등록수  0.902145
51    차량전체_등록수   하이브리드차_순증  0.893368
52    차량전체_등록수   차량전체_순증가량  0.871182
53   차량전체_순증가량   휘발유차_순증가량  0.937682
54   차량전체_순증가량    휘발유차_등록수  0.874809
55    평균기온(°C)  평균최저기온(°C)  0.994416
56    평균기온(°C)  평균최고기온(°C)  0.993329
57  평균최고기온(°C)  평균최저기온(°C)  0.976347
58  하이브리드차_등록수   하이브리드차_순증  0.980593
59  하이브리드차_등록수    휘발유차_등록수  0.896940
60   하이브리드차_순증    휘발유차_등록수  0.888483

In [ ]:
# 3) 종속변수 / 독립변수 분리
y = num_df_ori["전기차 등록수"]   
X = num_df_ori.drop(columns=["전기차 등록수"])     


#VIF 계산
X_const = add_constant(X)
vif_df = pd.DataFrame()
vif_df["변수"] = X_const.columns
vif_df["VIF"] = [variance_inflation_factor(X_const.values, i) 
                 for i in range(X_const.shape[1])]

#상수항 제거
vif_df = vif_df[vif_df["변수"] != "const"].reset_index(drop=True)
vif_df

c:\Users\jeon\anaconda3\envs\ev2_env\lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

                    변수           VIF
0             전기차 순증가량  2.060137e+00
1               연료소비효율  7.501179e+01
2             1회충전주행거리  5.726512e+01
3              배터리충전용량  6.907472e+00
4           완속충전기_신규설치           inf
5           급속충전기_신규설치           inf
6           전체충전기_신규설치           inf
7           완속충전기_누적대수           inf
8           급속충전기_누적대수           inf
9           전체충전기_누적대수           inf
10            차량전체_등록수  1.159657e+06
11           차량전체_순증가량  1.126870e+02
12             수소차_등록수  2.249394e+02
13            수소차_순증가량  5.969566e+00
14          하이브리드차_등록수  3.036414e+03
15           하이브리드차_순증  7.841473e+01
16            휘발유차_등록수  1.017070e+06
17           휘발유차_순증가량  5.717746e+01
18             경유차_등록수  7.993131e+03
19            경유차_순증가량  2.210320e+01
20            평균기온(°C)  3.565026e+03
21          평균최고기온(°C)  7.872361e+02
22          평균최저기온(°C)  1.099712e+03
23  월합강수량(00~24h만)(mm)  2.460832e+00
24          미세먼지2.5 수치  6.529116e+00
25           미세먼지10 수치  5.817866e+00
26                 cpi  6.569203e+01
27                 실업률  1.859343e+00
28              평균기준금리  3.397296e+01
29                경상소득  1.903016e+00
30                 보조금  1.469674e+01
31              민간공고대수  8.062519e+02
32                출고대수  6.228455e+02
33              출고잔여대수  4.524161e+01
34               휘발유가격  1.505684e+01
35                디젤가격  1.525395e+01

In [ ]:


num_df = num_df_ori.copy()

# 파생변수 생성

# 월별 평균 기온의 차이
num_df["월 기온차이"] = num_df["평균최저기온(°C)"] - num_df["평균최고기온(°C)"]

# 연료별 차량 증가 비율 
num_df["수소차 증가 비율"] = num_df["수소차_순증가량"] / num_df["차량전체_순증가량"]
num_df["하이브리드차 증가 비율"] = num_df["하이브리드차_순증"] / num_df["차량전체_순증가량"]
num_df["휘발유차 증가 비율"] = num_df["휘발유차_순증가량"] / num_df["차량전체_순증가량"]
num_df["경유차 증가 비율"] = num_df["경유차_순증가량"] / num_df["차량전체_순증가량"]
num_df["전기차 증가 비율"] = num_df["전기차 순증가량"] / num_df["차량전체_순증가량"]

# 충전기 종류 비율
num_df["충전기 종류 비율"] = num_df["완속충전기_누적대수"] / num_df["급속충전기_누적대수"] 
num_df["신규설치 충전기 종류 비율 "] = num_df["완속충전기_신규설치"] / num_df["급속충전기_신규설치"]

# 연료 가격 평균
num_df["휘발유 디젤 가격 평균"] = (num_df["휘발유가격"] + num_df["디젤가격"]) / 2

# 다중공선성 심한 변수 제거
num_df.drop(columns=[
    "완속충전기_신규설치", 
    "급속충전기_신규설치", 
    "전체충전기_신규설치", 
    "완속충전기_누적대수", 
    "급속충전기_누적대수",
    "평균최저기온(°C)",
    "평균최고기온(°C)",
    "차량전체_등록수",
    "1회충전주행거리",
    "하이브리드차_등록수",
    "수소차_등록수",
    "출고대수",
    "휘발유차_등록수",
    "경유차_등록수",
    "수소차_순증가량",
    "하이브리드차_순증",
    "휘발유차_순증가량",
    "경유차_순증가량",
    "차량전체_순증가량",
    "미세먼지10 수치",
    "휘발유가격",
    "디젤가격",
    "cpi",
    "전기차 순증가량"
    ,
    "휘발유차 증가 비율",
    "경유차 증가 비율"
    ], 
    inplace=True)


# 피어슨 상관계수 행렬
corr = num_df.corr(method="pearson")

corr.style.applymap(highlight_high_values)

C:\Users\jeon\AppData\Local\Temp\ipykernel_24860\4246766665.py:59: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  corr.style.applymap(highlight_high_values)

In [75]:
num_df.columns

Index(['전기차 등록수', '연료소비효율', '배터리충전용량', '전체충전기_누적대수', '평균기온(°C)',
       '월합강수량(00~24h만)(mm)', '미세먼지2.5 수치', '실업률', '평균기준금리', '경상소득', '보조금',
       '민간공고대수', '출고잔여대수', '월 기온차이', '수소차 증가 비율', '하이브리드차 증가 비율', '전기차 증가 비율',
       '충전기 종류 비율', '신규설치 충전기 종류 비율 ', '휘발유 디젤 가격 평균'],
      dtype='object')

In [ ]:
# 행렬을 긴 포맷으로 변환
corr_long = (
    corr.reset_index()
        .melt(id_vars="index", var_name="변수2", value_name="상관계수")
        .rename(columns={"index": "변수1"})
)
print(len(corr_long))
# 자기 자신과의 상관계수 제거
corr_long = corr_long[corr_long["변수1"] != corr_long["변수2"]]

# 변수1, 변수2 쌍 정렬해서 중복 제거
corr_long[["변수1", "변수2"]] = np.sort(corr_long[["변수1", "변수2"]], axis=1)
corr_long = corr_long.drop_duplicates(subset=["변수1", "변수2"])

# 상관계수 기준 정렬
corr_long = (
    corr_long[corr_long["상관계수"].abs() >= 0.8]  
    .sort_values(by=["변수1", "상관계수"], ascending=[True, False])
    .reset_index(drop=True)
)

corr_long

400

   변수1     변수2      상관계수
0  보조금  연료소비효율 -0.892566

In [77]:
# 3) 종속변수 / 독립변수 분리
y = num_df["전기차 등록수"]   
X = num_df.drop(columns=["전기차 등록수"])     


#VIF 계산
X_const = add_constant(X)
vif_df = pd.DataFrame()
vif_df["변수"] = X_const.columns
vif_df["VIF"] = [variance_inflation_factor(X_const.values, i) 
                 for i in range(X_const.shape[1])]

#상수항 제거
vif_df = vif_df[vif_df["변수"] != "const"].reset_index(drop=True)
vif_df

                    변수       VIF
0               연료소비효율  7.797087
1              배터리충전용량  1.458517
2           전체충전기_누적대수  3.722312
3             평균기온(°C)  3.549164
4   월합강수량(00~24h만)(mm)  2.242330
5           미세먼지2.5 수치  2.733078
6                  실업률  1.633192
7               평균기준금리  2.439234
8                 경상소득  1.661427
9                  보조금  8.873922
10              민간공고대수  3.113898
11              출고잔여대수  3.347026
12              월 기온차이  1.384397
13           수소차 증가 비율  1.439894
14        하이브리드차 증가 비율  1.413282
15           전기차 증가 비율  1.185018
16           충전기 종류 비율  1.031898
17     신규설치 충전기 종류 비율   1.049525
18        휘발유 디젤 가격 평균  1.859858